version: "3.9"
services:
  api:
    build: 
      context: ./apps/api-gateway
      dockerfile: Dockerfile
    env_file: ./apps/api-gateway/.env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api-gateway:/app

  workers:
    build: 
      context: ./apps/workers
      dockerfile: Dockerfile
    env_file: ./apps/workers/.env
    command: python worker.py
    volumes:
      - ./apps/workers:/app 