name: Railway Deploy
on: [push]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      
      - name: Deploy API Gateway
        run: |
          echo "Deploying API Gateway with token"
          railway logout || true
          railway up --service $RAILWAY_SERVICE_ID --detach ./apps/api-gateway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_API_GATEWAY }}
          RAILWAY_SERVICE_ID: 342c49f2-e2c6-4a08-8c86-40e822edbb9c
          RAILWAY_PROJECT_ID: 0f5e4e5a-09f8-4904-89a0-f3ed6c405bc3
          
  deploy-workers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      
      - name: Deploy Workers
        run: |
          echo "Deploying Workers with token"
          railway logout || true
          railway up --service $RAILWAY_SERVICE_ID --detach ./apps/workers
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_WORKERS }}
          RAILWAY_SERVICE_ID: 8d5f9fc1-262c-4223-ab72-9a83bc66fe27
          RAILWAY_PROJECT_ID: 7482e741-8ca2-453e-bc2f-a39c7680d145 