name: Railway Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc: [api-gateway, workers]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      
      - name: Deploy to Railway
        run: railway up --service ${{ matrix.svc }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 